version: '3.8'

services:
  proxy:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - cert_data:/etc/letsencrypt:ro
      - cert_challenge:/var/www/certbot:ro
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://database:27017/quizSystem
      - PORT=3000
      - SECRET=${SECRET}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

  database:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

  certbot:
    image: certbot/certbot
    volumes:
      - cert_data:/etc/letsencrypt
      - cert_challenge:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  mongo-data:
  cert_data:
  cert_challenge: